feature/CU-bgucr7_Create-game-preparation-wizard
Horsemen-and-Women-of-the-Apocalypse/bowling pull request #11
Opened 2020-12-30 21:17 UTC by Fantorem

2020-12-30 21:17 UTC, Fantorem commented
Task linked: [CU-bgucr7 Create game preparation wizard](https://app.clickup.com/t/bgucr7)

2020-12-30 23:35 UTC, Thurstag commented
Screen ?

2020-12-30 23:41 UTC, Thurstag requested changes

2020-12-30 23:41 UTC, Thurstag commented on src/App.vue
> +      <About/>
A renommer

2020-12-30 23:41 UTC, Thurstag commented on src/views/Home.vue
>  <template>
A renommer en `GamePreparation`

2020-12-30 23:41 UTC, Thurstag commented on tests/unit/pins.spec.js
> +    await wrapper.find(SubButtonSelector).trigger('click') // 10
Le `for` ça existe aussi xD

2020-12-30 23:41 UTC, Thurstag commented on tests/unit/turn.spec.js
> +    await wrapper.find(MinusButtonSelector).trigger('click') // 10
Le `for` ça existe aussi xD

2020-12-30 23:41 UTC, Thurstag commented on tests/e2e/specs/gameCreationWizard.js
> +    app.click('button[name=firstBtnValidate]')
Tu peux check la valeur

2020-12-30 23:41 UTC, Thurstag commented on tests/e2e/specs/gameCreationWizard.js
> +    app.click('button[name=secondBtnValidate]')
Tu peux check la valeur

2020-12-30 23:42 UTC, Thurstag commented
@Tomansion tu as test le drag avec le robot si c'est faisable ?

2020-12-31 07:24 UTC, Thurstag requested changes

2020-12-31 07:24 UTC, Thurstag commented on src/assets/lang/about.json
> +{
A renommer en `gamepreparation.json`

2020-12-31 07:24 UTC, Thurstag commented on src/views/Header.vue
> +  <div class="about">
`class=header`

2020-12-31 07:24 UTC, Thurstag commented on src/views/Header.vue
> +    <div id="gamePrep">{{ $t('about.prep')}}</div>
Ça devrait pas faire partit du composant `GamePreparation` car c'est en statique sur toutes les pages là

2020-12-31 07:27 UTC, Thurstag requested changes

2020-12-31 07:27 UTC, Thurstag commented on tests/e2e/specs/gameCreationWizard.js
> +  }
Il faut vérifier que si la liste des joueurs est vide le bouton jouer est désactivé

2020-12-31 08:36 UTC, Thurstag requested changes

2020-12-31 08:36 UTC, Thurstag commented on src/assets/lang/home.json
>        "home": {
A renommer en `gamepreparation.json`

2020-12-31 08:39 UTC, Thurstag requested changes

2020-12-31 08:39 UTC, Thurstag commented on src/views/Home.vue
>    <div class="home">
`class=gamepreparation`

2020-12-31 08:41 UTC, Thurstag commented
> Pc item1:
> ![image](https://user-images.githubusercontent.com/32369396/103388780-45a38580-4b0b-11eb-8d21-8f0c5360614f.png)
> Tel item1:
> ![image](https://user-images.githubusercontent.com/32369396/103388793-50f6b100-4b0b-11eb-9712-d25fd07f7580.png)
> Pc item2:
> ![image](https://user-images.githubusercontent.com/32369396/103388801-5e13a000-4b0b-11eb-8468-35a6a0c69909.png)
> Tel item2:
> ![image](https://user-images.githubusercontent.com/32369396/103388819-7388ca00-4b0b-11eb-915f-c04b7fc9e4e4.png)
> Pc item3:
> ![image](https://user-images.githubusercontent.com/32369396/103388848-81d6e600-4b0b-11eb-998e-df5b805ce4c7.png)
> Tel item3:
> ![image](https://user-images.githubusercontent.com/32369396/103388859-8e5b3e80-4b0b-11eb-8e11-14589ed82cae.png)

Pas moyen de centrer le stepper sur les grands écrans ?

2020-12-31 10:16 UTC, Tomansion commented on tests/e2e/specs/gameCreationWizard.js
> +    app.click('button[name=firstBtnValidate]')
à première vue c'est impossible, je n'ai pas pu faire un assert sur la valeur d'une input de manière fiable

2020-12-31 10:16 UTC, Tomansion commented on tests/e2e/specs/gameCreationWizard.js
> +    app.click('button[name=secondBtnValidate]')
idem

2020-12-31 11:18 UTC, Tomansion commented
> @Tomansion tu as test le drag avec le robot si c'est faisable ?

2020-12-31 11:36 UTC, Thurstag approved these changes

2020-12-31 11:36 UTC, Thurstag commented on src/views/Home.vue
> +      this.gameParam = new GameParam(this.players, turn, pins)
Il faut notifier l'utilisateur en cas d'erreur

2020-12-31 13:14 UTC, Thurstag requested changes

2020-12-31 13:14 UTC, Thurstag commented on src/App.vue
> +  height: 90vh;
100vh ou rien du coup

2020-12-31 16:23 UTC, YesLife approved these changes

2020-12-31 16:25 UTC, Fantorem commented on src/App.vue
> +  height: 90vh;
Le header fait 10vh

2020-12-31 16:26 UTC, Thurstag commented on src/App.vue
> +  height: 90vh;
c'est le composant root App

2020-12-31 18:39 UTC, Thurstag approved these changes

2020-12-31 18:39 UTC, merged