feature/CU-byyh0r_Fix-turns-and-pins-input-components
Horsemen-and-Women-of-the-Apocalypse/bowling pull request #13
Opened 2021-01-01 19:28 UTC by YesLife

2021-01-01 19:28 UTC, YesLife commented
Task linked: [CU-byyh0r Fix turns and pins input components](https://app.clickup.com/t/byyh0r)

2021-01-01 20:52 UTC, Tomansion approved these changes

2021-01-01 21:57 UTC, Thurstag requested changes

2021-01-01 21:57 UTC, Thurstag commented on tests/e2e/specs/gameCreationWizard.js
> +    for (let i = 11; i <= nbPins; i++) {
ce for sert à rien `11 <= 10`

2021-01-01 21:57 UTC, Thurstag commented on tests/e2e/specs/gameCreationWizard.js
> +    app.assert.elementCount('#errorMsg', 0)
Ce test sert à vérifier qu'il y a une popup en cas d'erreur donc soit tu enlèves le test car c'est impossible d'avoir une erreur soit tu trouves un moyen d'injecter une erreur et tu revert le changement

2021-01-01 21:57 UTC, Thurstag commented on src/components/Pins.vue
> +        this.count = 10
10 répété 3 fois, à mettre dans une constante

2021-01-01 21:57 UTC, Thurstag commented on src/components/Turn.vue
> +        this.count = 10
10 répété 3 fois, à mettre dans une constante

2021-01-01 23:08 UTC, Thurstag approved these changes

2021-01-03 16:01 UTC, Fantorem approved these changes

2021-01-03 16:04 UTC, merged