feature/CU-byxvkp_Create-an-automaton-for-turn-management
Horsemen-and-Women-of-the-Apocalypse/bowling pull request #17
Opened 2021-01-04 15:59 UTC by Fantorem

2021-01-04 15:59 UTC, Fantorem commented
Task linked: [CU-byxvkp Create an automaton for turn management](https://app.clickup.com/t/byxvkp)

2021-01-04 19:01 UTC, Thurstag requested changes

2021-01-05 10:54 UTC, Thurstag approved these changes

2021-01-05 12:05 UTC, Tomansion approved these changes

2021-01-05 13:28 UTC, YesLife approved these changes

2021-01-05 13:31 UTC, merged