Feature/cu byxv1c create an UI to announce player turn
Horsemen-and-Women-of-the-Apocalypse/bowling pull request #19
Opened 2021-01-05 13:32 UTC by LeBoyLeoz

2021-01-05 13:32 UTC, Thurstag commented
Task linked: [CU-byxv1c Create an UI to announce player turn](https://app.clickup.com/t/byxv1c)

2021-01-05 14:42 UTC, Thurstag requested changes

2021-01-05 14:42 UTC, Thurstag commented on src/components/PlayerAnouncement.vue
> +    font-family: Spicy Rice;
A supprimer quand la pr de la nouvelle palette sera mergée

2021-01-05 14:42 UTC, Thurstag commented on src/components/PlayerAnouncement.vue
> +    color: #F2C45A;
Changer la couleur quand la pr de la palette sera mergée

2021-01-05 14:42 UTC, Thurstag commented on src/components/PlayerAnouncement.vue
> +    font-size: 25px;
Utiliser em au lieu de px

2021-01-05 14:42 UTC, Thurstag commented on src/components/PlayerAnouncement.vue
> +        font-size: 32px;
Utiliser em au lieu de px

2021-01-05 14:42 UTC, Thurstag commented on src/components/PlayerAnouncement.vue
> +        font-size: 12px;
Utiliser em au lieu de px

2021-01-05 14:42 UTC, Thurstag commented on src/components/PlayerAnouncement.vue
> +        width: 100px;
Tu peux définir en % plutôt pour que ce soit responsive ?

2021-01-05 14:42 UTC, Thurstag commented on src/components/PlayerAnouncement.vue
> +        height: 100px;
Tu peux définir en % plutôt pour que ce soit responsive ?

2021-01-05 14:42 UTC, Thurstag commented on src/components/PlayerAnouncement.vue
> +        width: 100px;
Tu peux définir en % plutôt pour que ce soit responsive ?

2021-01-05 14:42 UTC, Thurstag commented on src/components/PlayerAnouncement.vue
> +        height: 100px;
Tu peux définir en % plutôt pour que ce soit responsive ?

2021-01-05 14:42 UTC, Thurstag commented on src/components/PlayerAnouncement.vue
> +        height: 28px;
Tu peux définir en % plutôt pour que ce soit responsive ?

2021-01-05 14:42 UTC, Thurstag commented on src/components/PlayerAnouncement.vue
> +        width: 28px;
Tu peux définir en % plutôt pour que ce soit responsive ?

2021-01-05 14:42 UTC, Thurstag commented on src/components/PlayerAnouncement.vue
> +    line-height: 32px;
Tu peux définir en % plutôt pour que ce soit responsive ?

2021-01-05 15:16 UTC, Fantorem approved these changes

2021-01-05 15:20 UTC, YesLife approved these changes

2021-01-07 15:26 UTC, Thurstag requested changes

2021-01-07 15:26 UTC, Thurstag commented on src/components/PlayerAnouncement.vue
> +    color: #B2A9C8;
Utiliser la palette

2021-01-07 15:26 UTC, Thurstag commented on src/components/PlayerAnouncement.vue
> +    color: #B2A9C8;
Utiliser la palette

2021-01-07 15:33 UTC, YesLife commented on src/components/PlayerAnouncement.vue
> +    font-family: SpicyRice-Regular;
Supprimer et utiliser .spicyRice de la palette ? (class="title spicyRice")

2021-01-07 15:46 UTC, Thurstag approved these changes

2021-01-07 15:50 UTC, merged

2021-01-07 16:08 UTC, Thurstag commented
![image](https://user-images.githubusercontent.com/28012414/103915060-fbbe2f00-510a-11eb-8f09-1576353541e8.png)