feature/CU-byxv22_Create-an-UI-for-player-turn
Horsemen-and-Women-of-the-Apocalypse/bowling pull request #25
Opened 2021-01-05 16:44 UTC by YesLife

2021-01-05 16:44 UTC, YesLife commented
Task linked: [CU-byxv22 Create an UI for player turn](https://app.clickup.com/t/byxv22)

2021-01-05 23:06 UTC, Thurstag requested changes

2021-01-05 23:06 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +    sub2: function (e) { // Remove 1 to number of pins fallen on the second throw
subSecondThrow

2021-01-05 23:06 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +    updatepinsFallen1: function (e) { // Update pins count1 if value >= 0
`updateFirstThrowFallenPins`

2021-01-05 23:06 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +    updatepinsFallen2: function (e) { // Update pins count2 if value >= 0
`updateSecondThrowFallenPins`

2021-01-05 23:06 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +  background-color: #bfb35a !important;
Mettre à jour avec la nouvelle palette

2021-01-05 23:06 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +  background-color: #BFB35A;
Mettre à jour avec la nouvelle palette

2021-01-05 23:06 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +  background-color: #88A65E !important;
Mettre à jour avec la nouvelle palette

2021-01-05 23:06 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +  color: #88A65E;
Mettre à jour avec la nouvelle palette

2021-01-05 23:06 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +  color: #8C2318;
Mettre à jour avec la nouvelle palette

2021-01-06 01:44 UTC, Thurstag requested changes

2021-01-06 01:44 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +    updatepinsFallen1: function (e) { // Update pins count1 if value >= 0
`updateFirstCount`

2021-01-06 01:44 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +    updatepinsFallen2: function (e) { // Update pins count2 if value >= 0
`updateSecondCount`

2021-01-07 10:38 UTC, Thurstag requested changes

2021-01-07 10:38 UTC, Thurstag commented on src/assets/lang/playerTurn.json
> +      "reset": "Cancel"
A inverser

2021-01-07 10:41 UTC, Thurstag requested changes

2021-01-07 10:41 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +  height: 90vh;
en %

2021-01-07 12:05 UTC, Thurstag requested changes

2021-01-07 12:05 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +            <div class="md-layout-item">
Rajouter `md-size-25`

2021-01-07 12:05 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +            <div class="md-layout-item">
Rajouter `md-size-50`

2021-01-07 12:05 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +            <div class="md-layout-item">
Rajouter `md-size-25`

2021-01-07 12:05 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +            <div class="md-layout-item">
Rajouter `md-size-25`

2021-01-07 12:05 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +            <div class="md-layout-item">
Rajouter `md-size-50`

2021-01-07 12:05 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +            <div class="md-layout-item">
Rajouter `md-size-25`

2021-01-07 12:51 UTC, YesLife commented
First Turn PC :

2021-01-07 12:57 UTC, Thurstag requested changes

2021-01-07 12:57 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +  color: #8c2318;
A changer

2021-01-07 12:59 UTC, Thurstag requested changes

2021-01-07 12:59 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +              <md-button id='decrementSecondThrow' v-on:click="decrementSecondThrow" class="md-icon-button">
Rajouter `md-raised`

2021-01-07 12:59 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +              <md-button id='incrementSecondThrow' v-on:click="incrementSecondThrow" class="md-icon-button">
Rajouter `md-raised`

2021-01-07 12:59 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +              <md-button id='decrementFirstThrow' v-on:click="decrementFirstThrow" class="md-icon-button">
Rajouter `md-raised`

2021-01-07 12:59 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +              <md-button id='incrementFirstThrow' v-on:click="incrementFirstThrow" class="md-icon-button">
Rajouter `md-raised`

2021-01-07 16:02 UTC, LeBoyLeoz commented
![image](https://user-images.githubusercontent.com/48457627/103914412-1348e800-510a-11eb-918a-5c66589be3a8.png)

2021-01-07 16:45 UTC, Tomansion approved these changes
Les bon petits conflits qui nous attendent

2021-01-07 19:42 UTC, Thurstag requested changes

2021-01-07 19:42 UTC, Thurstag commented on tests/unit/playerTurn.spec.js
> +    await wrapper.find('input[name=pinsFallen2]').setValue(12)
c'est un bug que tu puisses écrire dans le texte du 2e lancer alors que tu as fais un strike

2021-01-07 21:54 UTC, YesLife commented on tests/unit/playerTurn.spec.js
> +    await wrapper.find('input[name=pinsFallen2]').setValue(12)
![image](https://user-images.githubusercontent.com/70711818/103948488-24115200-513a-11eb-8f59-6f205c6b8775.png)
Comme tu peux le voir, le bouton disparaît du code HTML de la page de l'utilisateur, c'est uniquement possible dans le test car le bot fait tout en même temps sans rafraîchir la page (il saisit 10 puis clique sur le bouton "Suivant" sans que l'interface de départ ne se mette à jour)
Mais je suis d'accord, je supprime cette partie vu qu'elle ne sert à rien

2021-01-08 18:35 UTC, Fantorem requested changes

2021-01-08 18:35 UTC, Fantorem commented on src/components/PlayerTurn.vue
> +    count2 () {
count1 et count2 ? Commentaires ou changer le non de fonction. Pas de count3 ?

2021-01-08 18:35 UTC, Fantorem commented on src/components/PlayerTurn.vue
> +    Reliez_moi_svp () {
nom de fonction

2021-01-08 18:35 UTC, Fantorem commented on src/components/PlayerTurn.vue
> +    count3: 0,
count de quoi ?

2021-01-08 18:36 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +    Reliez_moi_svp () {
C'est fait exprès, c'est toi qui va la renommer

2021-01-08 18:37 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +    count3: 0,
C'est:
* `firstThrow`
* `secondThrow`
* `thirdThrow`

2021-01-08 18:40 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +    Reliez_moi_svp () {
`terminate` pour s'aligner avec le code de Tom

2021-01-08 18:43 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +    count2 () {
On est sur un tour commun donc que deux lancers, il n'y a que le dernier qui contient trois lancers

2021-01-08 19:41 UTC, LeBoyLeoz commented on src/components/PlayerTurn.vue
> +    count3: 0,
```
    firstThrow: 0,
    secondThrow: 0,
    thirdThrow: 0,
```

2021-01-09 13:46 UTC, merged