feature/CU-c2xwtq_Create-an-UI-for-last-player-turn
Horsemen-and-Women-of-the-Apocalypse/bowling pull request #26
Opened 2021-01-07 11:44 UTC by Tomansion

WIP

2021-01-07 11:44 UTC, Tomansion commented
Task linked: [CU-c2xwtq Create an UI for last player turn](https://app.clickup.com/t/c2xwtq)

2021-01-07 11:53 UTC, Thurstag requested changes

2021-01-07 11:53 UTC, Thurstag commented on src/components/LastPlayerTurn.vue
> +  background: var(--accent) !important;
A supprimer

2021-01-07 11:53 UTC, Thurstag commented on src/components/LastPlayerTurn.vue
> +            class="terminate md-raised md-primary"
Enlever le md-primary et le terminate, puis mettre md-accent

2021-01-07 11:53 UTC, Thurstag commented on src/components/LastPlayerTurn.vue
> +            class="terminate md-raised md-primary"
Enlever le md-primary et le terminate, puis mettre md-accent

2021-01-07 11:53 UTC, Thurstag commented on src/components/LastPlayerTurn.vue
> +        <h1 class="pageTitle">{{ $t("lastPlayerTurn.first") }}</h1>
A supprimer

2021-01-07 11:53 UTC, Thurstag commented on src/components/LastPlayerTurn.vue
> +        <h1 class="pageTitle">{{ $t("lastPlayerTurn.second") }}</h1>
A supprimer

2021-01-07 11:53 UTC, Thurstag commented on src/components/LastPlayerTurn.vue
> +        <h1 class="pageTitle">{{ $t("lastPlayerTurn.third") }}</h1>
A supprimer

2021-01-07 13:13 UTC, Thurstag requested changes

2021-01-07 13:13 UTC, Thurstag commented on src/components/LastPlayerTurn.vue
> +  color: #8c2318;
A changer

2021-01-07 17:16 UTC, YesLife approved these changes

2021-01-07 17:35 UTC, Thurstag requested changes

2021-01-07 17:35 UTC, Thurstag commented on src/assets/lang/playerTurn.json
> +      "inputTitle": "Number of fallen pins :",
Il faut afficher le nombre de quilles restantes (cf: pr de nathan)

2021-01-07 17:35 UTC, Thurstag commented on src/assets/lang/playerTurn.json
> +      "inputTitle": "Nombre de quilles tombées :",
Il faut afficher le nombre de quilles restantes (cf: pr de nathan)

2021-01-07 18:02 UTC, Thurstag requested changes

2021-01-07 18:04 UTC, Thurstag requested changes

2021-01-07 18:04 UTC, Thurstag commented on src/components/LastPlayerTurn.vue
> +                :min="0"
A enlever

2021-01-07 18:04 UTC, Thurstag commented on src/components/LastPlayerTurn.vue
> +                :max="totalPins"
A enlever

2021-01-07 18:04 UTC, Thurstag commented on src/components/LastPlayerTurn.vue
> +                :min="0"
A enlever

2021-01-07 18:04 UTC, Thurstag commented on src/components/LastPlayerTurn.vue
> +                :max="maxPinsSecondThrow"
A enlever

2021-01-07 18:04 UTC, Thurstag commented on src/components/LastPlayerTurn.vue
> +                :min="0"
A enlever

2021-01-07 18:04 UTC, Thurstag commented on src/components/LastPlayerTurn.vue
> +                :max="maxPinsThirdThrow"
A enlever

2021-01-08 18:35 UTC, Fantorem requested changes

2021-01-08 18:35 UTC, Fantorem commented on src/components/LastPlayerTurn.vue
> +    count3: 0,
Nom de variable à changer

2021-01-08 18:53 UTC, LeBoyLeoz approved these changes
Je vois rien de choquant !

2021-01-09 12:48 UTC, YesLife commented on src/components/LastPlayerTurn.vue
> +    count3: 0,
firstThrow: 0,
secondThrow: 0,
thirdThrow: 0,

2021-01-09 15:22 UTC, Tomansion commented on src/components/LastPlayerTurn.vue
> +      this.active = 'third'
à cause du button vif dans le template. si du texte est rentré dans le champ N°2, c'est la fonction terminate qui est appelé et pas  validateSecond
donc même si le if n'est pas inutile, il est impossible de le tester et d'avoir 100% de coverage au niveau des branches

2021-01-09 15:22 UTC, Tomansion commented on tests/unit/lastPlayerTurn.spec.js
> +    await wrapper.find('button[name=thirdBtnValidate]').trigger('click')
la valeur n'est pas reset dans mon cas

2021-01-09 15:23 UTC, Tomansion commented on src/components/LastPlayerTurn.vue
> +                :max="totalPins"
vraiment ? c'est pas perdu pourtant

2021-01-09 15:44 UTC, Thurstag requested changes

2021-01-09 15:44 UTC, Thurstag commented on src/components/LastPlayerTurn.vue
> +              <md-input
Il manque le type number

2021-01-09 16:32 UTC, Thurstag approved these changes

2021-01-09 16:44 UTC, merged