feature/CU-byxvmn_Create-an-UI-for-game-run
Horsemen-and-Women-of-the-Apocalypse/bowling pull request #29
Opened 2021-01-10 17:30 UTC by Fantorem

WIP (pas de tests)

2021-01-10 17:30 UTC, Fantorem commented
Task linked: [CU-byxvmn Create an UI for game run](https://app.clickup.com/t/byxvmn)

2021-01-10 17:56 UTC, Thurstag requested changes

2021-01-10 17:56 UTC, Thurstag commented on src/views/ScoreboardView.vue
> +            <md-button class="md-raised md-raised md-primary" @click="goToHome">{{$t('scoreBoard.back')}}</md-button>
`md-raised` en doublon

2021-01-10 17:56 UTC, Thurstag commented on src/views/Game.vue
> +    lastTurn: false
Créer une méthode dans l'automate `isLastTurn`

2021-01-10 17:56 UTC, Thurstag commented on src/views/Game.vue
> +      // this.gameScore.registerThrow(this.automaton.getCurrentPlayer().getName(), this.automaton.getCurrentTurn() + 1, 1, throws.throw1) // A décommenter pour la tâche Fill score board
Enregistrer les lancers c'est ta tâche

2021-01-10 17:56 UTC, Thurstag commented on src/views/Game.vue
> +      // this.gameScore.registerThrow(this.automaton.getCurrentPlayer().getName(), this.automaton.getCurrentTurn() + 1, 2, throws.throw2) // A décommenter pour la tâche Fill score board
Enregistrer les lancers c'est ta tâche

2021-01-10 17:56 UTC, Thurstag commented on src/objets/gameScore.js
> +     *
Documentation

2021-01-10 17:56 UTC, Thurstag commented on src/objets/gameScore.js
> +     *
Documentation

2021-01-10 17:56 UTC, Thurstag commented on src/objets/gameScore.js
> +     *
Documentation

2021-01-10 17:56 UTC, Thurstag commented on src/objets/gameScore.js
> +     *
Documentation + renommer en `getThrow`

2021-01-10 17:56 UTC, Thurstag commented on src/objets/gameScore.js
> +     *
Documentation + renommmer en `getThrows`

2021-01-10 17:56 UTC, Thurstag commented on src/objets/gameScore.js
> +    #playerScores = []
Renommer en `playerThrows`

2021-01-10 17:56 UTC, Thurstag commented on src/views/Game.vue
> +    nextTurn (throws) {
Il est où l'enregistrement du 3e lancer du dernier tour ?

2021-01-10 17:56 UTC, Thurstag commented on src/assets/lang/game.json
> +        "confirm": "Validate the throw"
Utiliser nulle part

2021-01-10 17:56 UTC, Thurstag commented on src/components/GameHeader.vue
> +    <div class="spicyRice" id="title">{{ $t('scoreBoard.turn')}}</div>
Au lieu de faire un copier-coller tu peux pas un faire un composant avec les deux div modulaires et possèdant les props: title, subTitle

2021-01-10 18:11 UTC, Fantorem commented on src/components/GameHeader.vue
> +    <div class="spicyRice" id="title">{{ $t('scoreBoard.turn')}}</div>
A ajouter dans une autre tâche

2021-01-10 18:12 UTC, Thurstag requested changes

2021-01-10 18:12 UTC, Thurstag commented on src/components/GameHeader.vue
> +    <div class="spicyRice" id="title">{{ $t('scoreBoard.turn')}}</div>
non tu fais un copier-coller donc c'est ton boulot de factoriser le code

2021-01-10 18:25 UTC, Thurstag requested changes

2021-01-10 18:25 UTC, Thurstag commented on src/assets/lang/scoreBoard.json
> +      "turn": "Turn of"
C'est dans le déroulement de la partie cette string donc rien à faire dans le scoreboard

2021-01-10 19:47 UTC, Thurstag requested changes

2021-01-10 19:47 UTC, Thurstag commented on src/views/ScoreboardView.vue
> +import Scoreboard from '../components/scoreboard/ScoreBoard'
ton import est pas bon

2021-01-10 19:58 UTC, Fantorem commented on src/views/ScoreboardView.vue
> +import Scoreboard from '../components/scoreboard/ScoreBoard'
En local si

2021-01-10 19:59 UTC, Thurstag commented on src/views/ScoreboardView.vue
> +import Scoreboard from '../components/scoreboard/ScoreBoard'
bah c'est ce que le build dit en terme d'erreur

2021-01-10 19:59 UTC, Fantorem commented on src/views/ScoreboardView.vue
> +import Scoreboard from '../components/scoreboard/ScoreBoard'
Je sais bien

2021-01-10 23:44 UTC, Thurstag requested changes

2021-01-10 23:44 UTC, Thurstag commented on tests/e2e/specs/gameWizard.js
> +function firstPage (browser, cnbTurn, cnbPins, cnbPlayers) {
Pourquoi tu testes la préparation de la partie, ça déjà été fait donc cette fonction doit juste remplir les champs comme un utilisateur sans vérifier le contenu comme le ferait un test

2021-01-10 23:44 UTC, Thurstag commented on tests/e2e/specs/gameWizard.js
> +    app.assert.visible('button[name=thirdBtnValidate]')
Il est où le 3e lancer ? tu fais rien là

2021-01-10 23:44 UTC, Thurstag commented on tests/e2e/specs/gameWizard.js
> +    app.click('button[name=secondBtnValidate]')
Assert le contenu du tableau pour vérifier que les lancers sont bien enregistrés

2021-01-10 23:44 UTC, Thurstag commented on tests/e2e/specs/gameWizard.js
> +    app.assert.visible('button[name=thirdBtnValidate]')
Assert le contenu du tableau pour vérifier que les lancers sont bien enregistrés

2021-01-10 23:44 UTC, Thurstag commented on tests/unit/objects.spec.js
> +    describe('getParam', () => {
isLastTurn

2021-01-11 07:26 UTC, Thurstag requested changes

2021-01-11 07:26 UTC, Thurstag commented on src/views/Game.vue
> +      if (this.automaton.isLastTurn()) { this.gameScore.registerThrow(this.automaton.getCurrentPlayer().getName(), this.automaton.getCurrentTurn() + 1, 3, throws.throw3) }
Il n'y a pas toujours un 3e lancer donc il ne faut pas l'enregistrer tout le temps

2021-01-11 07:58 UTC, Thurstag requested changes

2021-01-11 07:58 UTC, Thurstag commented on src/views/Game.vue
> +      this.gameScore.registerThrow(this.automaton.getCurrentPlayer().getName(), this.automaton.getCurrentTurn() + 1, 2, throws.throw2)
Pareil si on fait un strike dans un tour commun il ne faut pas enregistrer le 2e lancer

2021-01-11 08:11 UTC, Thurstag requested changes

2021-01-11 08:11 UTC, Thurstag commented on src/views/Game.vue
> +      if (throws.throw1 < 10) { this.gameScore.registerThrow(this.automaton.getCurrentPlayer().getName(), this.automaton.getCurrentTurn() + 1, 2, throws.throw2) }
Génial le nombre de quilles en dur qui est faux

2021-01-11 08:11 UTC, Thurstag commented on src/views/Game.vue
> +      if (this.automaton.isLastTurn() && (throws.throw1 + throws.throw2 >= 10)) { this.gameScore.registerThrow(this.automaton.getCurrentPlayer().getName(), this.automaton.getCurrentTurn() + 1, 3, thr
Génial le nombre de quilles en dur qui est faux

2021-01-11 08:11 UTC, Thurstag commented on src/views/Game.vue
> +      if (throws.throw1 < 10) { this.gameScore.registerThrow(this.automaton.getCurrentPlayer().getName(), this.automaton.getCurrentTurn() + 1, 2, throws.throw2) }
Faux, lors du 3e lancer tu peux faire un strike et tu as le droit à un 2e lancer. Indice: Il faut modifier les composants de PlayerTurn & LastPlayerTurn pour que dans l'event un lancer non effectué soit symbolisé par un undefined et dans cette fonction tu as juste à tester si throwX est différent d'undefined pour enregistrer un lancer

2021-01-11 08:18 UTC, Thurstag requested changes

2021-01-11 08:18 UTC, Thurstag commented on tests/e2e/specs/gameWizard.js
> +  players.forEach((playerName, i) => {
A enlever

2021-01-11 08:18 UTC, Thurstag commented on tests/e2e/specs/gameWizard.js
> +  app.getAttribute('button[name=thirdBtnValidate]', 'disabled', result => { app.assert.equal(result.value, null) })
A enlever

2021-01-11 08:18 UTC, Thurstag commented on tests/e2e/specs/gameWizard.js
> +    app.assert.elementPresent('#PlayerListCreator #player_' + (i + 1))
A enlever

2021-01-11 08:18 UTC, Thurstag commented on tests/e2e/specs/gameWizard.js
> +  app.assert.attributeEquals('button[name=thirdBtnValidate]', 'disabled', 'true')
A enlever

2021-01-11 08:18 UTC, Thurstag commented on tests/e2e/specs/gameWizard.js
> +  app.assert.visible('button[name=thirdBtnValidate]')
A enlever

2021-01-11 08:18 UTC, Thurstag commented on tests/e2e/specs/gameWizard.js
> +  app.assert.visible('input[name=newPlayerName]')
A enlever

2021-01-11 08:18 UTC, Thurstag commented on tests/e2e/specs/gameWizard.js
> +    app.assert.value('input[name=pinsCount]', '' + i)
A enlever

2021-01-11 08:18 UTC, Thurstag commented on tests/e2e/specs/gameWizard.js
> +  app.assert.value('input[name=pinsCount]', '10')
A enlever

2021-01-11 08:18 UTC, Thurstag commented on tests/e2e/specs/gameWizard.js
> +  app.assert.visible('button[name=secondBtnValidate]')
A enlever

2021-01-11 08:18 UTC, Thurstag commented on tests/e2e/specs/gameWizard.js
> +  app.assert.visible('input[name=pinsCount]')
A enlever

2021-01-11 08:18 UTC, Thurstag commented on tests/e2e/specs/gameWizard.js
> +    app.assert.value('input[name=turnCount]', '' + (i - 1))
A enlever

2021-01-11 08:18 UTC, Thurstag commented on tests/e2e/specs/gameWizard.js
> +  app.assert.value('input[name=turnCount]', '10')
A enlever

2021-01-11 08:18 UTC, Thurstag commented on tests/e2e/specs/gameWizard.js
> +  app.assert.visible('button[name=firstBtnValidate]')
A enlever

2021-01-11 08:18 UTC, Thurstag commented on tests/e2e/specs/gameWizard.js
> +  app.assert.visible('input[name=turnCount]')
A enlever

2021-01-11 08:26 UTC, Thurstag commented
Il est où l'affichage du tour ?

2021-01-11 08:27 UTC, Fantorem commented
> Il est où l'affichage du tour ?

L'affichage de l'animation ?

2021-01-11 08:28 UTC, Thurstag commented
> > Il est où l'affichage du tour ?
> 
> L'affichage de l'animation ?

Non `$CURRENT_TURN/$TURNS_COUNT` (c.f: mockup)

2021-01-11 09:19 UTC, Thurstag requested changes

2021-01-11 09:19 UTC, Thurstag commented on src/components/LastPlayerTurn.vue
> +    throw3: undefined,
C'est 100% pas stable avec la correction automatique, limite rajoute un argument à `terminate()` pour savoir dans quel cas tu es et ce que tu dois mettre à undefined

2021-01-11 09:19 UTC, Thurstag commented on src/components/PlayerTurn.vue
> +    secondThrow: undefined,
Pareil que le commentaire de LastPlayerTurn

2021-01-11 09:21 UTC, Thurstag requested changes

2021-01-11 09:21 UTC, Thurstag commented on src/views/Game.vue
> +         <h2>Tour {{this.automaton.getCurrentTurn() + 1}} / {{this.automaton.getGameParam().getTurn()}}</h2>
* Pas d'i18n
* C'est moche, c'est affiché dans le stepper (tu peux rajouter une troisième ligne à Header sinon)

2021-01-11 09:25 UTC, Fantorem commented on src/components/LastPlayerTurn.vue
> +    throw3: undefined,
Le truc c'est que ça reste à undefined si la suite du steppers est pas affiché donc pas d'action sur la variable.

2021-01-11 09:25 UTC, Fantorem commented on src/components/PlayerTurn.vue
> +    secondThrow: undefined,
Idem

2021-01-11 09:37 UTC, Thurstag requested changes

2021-01-11 09:37 UTC, Thurstag commented on src/components/LastPlayerTurn.vue
> +    throw3: undefined,
Tu as oublié de mettre à undefined quand on fait retour ce qui génère un bug donc c'est pas une solution fiable car même toi tu ne l'as pas implémenté correctement.

Ex: Tu rajoutes un booléen à terminate qui indique si on a fait 3 lancers ou 2 lancers et c'est réglé en deux deux sans introduction de bug

2021-01-11 12:23 UTC, YesLife approved these changes

2021-01-11 13:28 UTC, Thurstag approved these changes

2021-01-11 13:30 UTC, Tomansion approved these changes

2021-01-11 13:30 UTC, merged