feature/CU-ccuhqj_Add-a-button-to-go-to-home-screen
Horsemen-and-Women-of-the-Apocalypse/bowling pull request #31
Opened 2021-01-11 16:39 UTC by Tomansion

2021-01-11 16:39 UTC, Tomansion commented
Task linked: [CU-ccuhqj Add a button to go to home screen](https://app.clickup.com/t/ccuhqj)

2021-01-11 16:45 UTC, Thurstag approved these changes

2021-01-11 16:49 UTC, Fantorem requested changes
Police ?

2021-01-11 16:49 UTC, YesLife approved these changes

2021-01-11 20:55 UTC, furtivesock commented
> 
> 
> Police

La police utilisée pour le texte, Raleway
Le bouton Home doit être de couleur rouge (primary)

2021-01-11 20:55 UTC, Fantorem requested changes

2021-01-11 20:55 UTC, Fantorem commented on src/views/Game.vue
> +        <md-button class="md-fab md-fab-bottom-right md-plain" name="goToHome" @click="confirmExitDialog = true">
Couleur du bouton : md-primary

2021-01-11 20:55 UTC, Fantorem commented on src/views/Game.vue
> +        name="confirmExitDialog">
Ajouter class : ralewayRegular

2021-01-12 11:02 UTC, Tomansion commented on src/views/Game.vue
> +        <md-button class="md-fab md-fab-bottom-right md-plain" name="goToHome" @click="confirmExitDialog = true">
![image](https://user-images.githubusercontent.com/59999324/104306297-10fdd980-54ce-11eb-8f84-493b473a666d.png)
C'est bon comme ça ?

2021-01-12 11:25 UTC, merged