feature/CU-ccwze4_Fix-turn-data-destroyed-by-page-change
Horsemen-and-Women-of-the-Apocalypse/bowling pull request #34
Opened 2021-01-11 21:37 UTC by Fantorem

2021-01-11 21:37 UTC, Fantorem commented
Task linked: [CU-ccwze4 Fix turn data destroyed by page change](https://app.clickup.com/t/ccwze4)

2021-01-11 21:56 UTC, Thurstag approved these changes

2021-01-12 10:58 UTC, Tomansion approved these changes

2021-01-12 14:27 UTC, YesLife approved these changes

2021-01-12 16:58 UTC, Thurstag requested changes

2021-01-12 16:58 UTC, Thurstag commented on src/App.vue
> +      <keep-alive>
Rajouter un test d'intégration

2021-01-12 17:16 UTC, Thurstag approved these changes

2021-01-12 17:17 UTC, merged