feature/CU-bguc5w_Create-data-related-to-game-preparation
Horsemen-and-Women-of-the-Apocalypse/bowling pull request #6
Opened 2020-12-20 13:18 UTC by Fantorem

2020-12-20 13:18 UTC, Fantorem commented
Task linked: [CU-bguc5w Create data related to game preparation](https://app.clickup.com/t/bguc5w)

2020-12-20 13:25 UTC, Tomansion commented on src/objets/gameparam.js
> +    getPlayerAt (pos) {
C'est obligé les getters ?
les attributs ne sont pas public ?

2020-12-20 13:28 UTC, Tomansion commented on tests/unit/objects.spec.js
> +  test('Assert contents', () => {
'Assert contents', c'est le nom du test ?
On peux le changer ?

2020-12-20 14:17 UTC, Thurstag requested changes

2020-12-20 14:17 UTC, Thurstag commented on src/objets/gameparam.js
> +export default class GameParam {
Manque la documentation

2020-12-20 14:17 UTC, Thurstag commented on src/objets/gameparam.js
> +    constructor (cplayers, ccount, cpins) {
Pas de documentation ni de tests pour vérifier que les paramètres sont conformes

2020-12-20 14:17 UTC, Thurstag commented on src/objets/gameparam.js
> +    * @param {int} pos - Position in list
Documenté à moitié

2020-12-20 14:17 UTC, Thurstag commented on src/objets/gameparam.js
> +    getPlayers () {
Pas de documentation

2020-12-20 14:17 UTC, Thurstag commented on src/objets/gameparam.js
> +    * @param {Player} player - Player
Documenté à moitié + pas de vérification du paramètre

2020-12-20 14:17 UTC, Thurstag commented on src/objets/gameparam.js
> +    getPlayerAt (pos) {
Il faut vérifier l'indice donné

2020-12-20 14:17 UTC, Thurstag commented on src/objets/gameparam.js
> +    removePlayer (player) {
Pas de vérification du paramètre et documenté à moitié

Et si le player n'est pas dans la liste ?

2020-12-20 14:17 UTC, Thurstag commented on src/objets/gameparam.js
> +    * @param {int} pos - Position in list
Documenté à moitié

2020-12-20 14:17 UTC, Thurstag commented on src/objets/gameparam.js
> +    removePlayerFromIndex (pos) {
Paramètre non vérifié

2020-12-20 14:17 UTC, Thurstag commented on src/objets/gameparam.js
> +      this.players.splice(this.players.indexOf(player), 1)
`removePlayerFromIndex(this.players.indexOf(player))` pour réutiliser du code

2020-12-20 14:17 UTC, Thurstag commented on src/objets/gameparam.js
> +    getCount () {
Pas de documentation

2020-12-20 14:17 UTC, Thurstag commented on src/objets/gameparam.js
> +    getPins () {
Pas de documentation

2020-12-20 14:17 UTC, Thurstag commented on src/objets/player.js
> +export default class Player {
Pas de documentation

2020-12-20 14:17 UTC, Thurstag commented on src/objets/player.js
> +    constructor (cname) {
Pas de documentation et de vérification du paramètre

2020-12-20 14:17 UTC, Thurstag commented on src/objets/player.js
> +    getName () {
Pas de documentation

2020-12-20 14:17 UTC, Thurstag commented on tests/unit/objects.spec.js
> +  test('Assert contents', () => {
C'est un peu le bordel ton fichier de test. Si tu veux faire ça proprement on a tendance à faire:
```js
describe('$ClassName', () => {
  describe('#$MethodName', () => {
    test('$Expected_behaviour', () => {
      // Write assertions here
    })
  })
})
```

2020-12-20 16:52 UTC, Thurstag requested changes

2020-12-20 16:52 UTC, Thurstag commented on src/objets/gameparam.js
> +    getPlayerAt (pos) {
Tu as vérifié le type mais pas la valeur

2020-12-20 16:52 UTC, Thurstag commented on src/objets/gameparam.js
> +    removePlayerFromIndex (pos) {
Le type est vérifié mais pas la valeur

2020-12-20 16:52 UTC, Thurstag commented on src/objets/gameparam.js
> +    * @param {int} ccount - number of count
Number of turns

2020-12-20 16:52 UTC, Thurstag commented on src/objets/gameparam.js
> +    constructor (cplayers, ccount, cpins) {
ccount -> cturns

2020-12-20 16:52 UTC, Thurstag commented on src/objets/gameparam.js
> +      if (Number.isInteger(ccount)) {
Le type est vérifié mais pas la valeur

2020-12-20 16:52 UTC, Thurstag commented on src/objets/gameparam.js
> +      if (Number.isInteger(cpins)) {
Le type est vérifié mais pas la valeur

2020-12-20 16:56 UTC, Thurstag requested changes

2020-12-20 16:56 UTC, Thurstag commented on src/objets/gameparam.js
> +      cplayers.forEach(function (item, index, array) {
Si cplayers n'est pas une array ?

2020-12-20 17:09 UTC, Fantorem commented on src/objets/gameparam.js
> +    getPlayerAt (pos) {
Plus propre de récup les infos via la l'objet au lieu de récup la list puis récup les infos de la list via celle-ci

2020-12-20 17:09 UTC, Thurstag approved these changes

2020-12-21 08:54 UTC, Tomansion approved these changes

2020-12-21 18:47 UTC, YesLife approved these changes

2020-12-21 18:59 UTC, merged