feature/CU-bf24du_Add-continuous-deployment
Horsemen-and-Women-of-the-Apocalypse/bowling pull request #7
Opened 2020-12-20 13:18 UTC by Tomansion

GitHub secrets and server script are already set

2020-12-20 13:18 UTC, Tomansion commented
Task linked: [CU-bf24du Add continuous deployment](https://app.clickup.com/t/bf24du)

2020-12-20 14:20 UTC, Thurstag commented on .github/workflows/cd.yml
> +        script: ./updateapp.sh
C'est un script sur la machine où l'image est déployée ou un script dans le repo ?

2020-12-20 14:20 UTC, Thurstag commented on .github/workflows/cd.yml
> +        uses: svenstaro/upload-release-action@v1-release
Ça créé une release automatiquement car en regardant la doc ça attache juste un pièce jointe à la dernière release non ?

2020-12-20 15:02 UTC, Tomansion commented on .github/workflows/cd.yml
> +        script: ./updateapp.sh
Il s'agit d'un script présent sur la machine hôte

Si tu veux le voir, je ne peux pas te le montrer maintenant.
Mais en gros il télécharge le .tar de la release lance un conteneur

2020-12-20 15:03 UTC, Tomansion commented on .github/workflows/cd.yml
> +        uses: svenstaro/upload-release-action@v1-release
Ça crée une release si elle n'existe pas.

Je peux essayer d'ajouter la date pour créer une nouvelle réaliste à chaque fois

2020-12-20 16:10 UTC, YesLife approved these changes

2020-12-20 16:26 UTC, Thurstag commented on .github/workflows/cd.yml
> +        script: ./updateapp.sh
Ok, je voulais juste savoir c'était quoi ce script et où il est

2020-12-20 16:27 UTC, Thurstag commented on .github/workflows/cd.yml
> +        uses: svenstaro/upload-release-action@v1-release
Dans ce cas là, va chercher la version dans le package.json pour le nom de la release

2020-12-20 16:29 UTC, Fantorem approved these changes

2020-12-20 18:37 UTC, Tomansion commented on .github/workflows/cd.yml
> +        uses: svenstaro/upload-release-action@v1-release
excellenteidée

2020-12-21 08:53 UTC, Tomansion commented on .github/workflows/cd.yml
> +        uses: svenstaro/upload-release-action@v1-release
J'ai apporté les modif

2020-12-21 18:09 UTC, Thurstag commented
Attends, il est où ton Dockerfile ?

2020-12-21 18:13 UTC, Thurstag requested changes

2020-12-21 18:13 UTC, Thurstag commented on .github/workflows/cd.yml
> +        run: docker build . -t ${{env.docker-img-name}}
Il est où ton Dockerfile ?

2020-12-22 09:02 UTC, Tomansion commented on .github/workflows/cd.yml
> +        run: docker build . -t ${{env.docker-img-name}}
ah fuck

2020-12-22 18:00 UTC, Thurstag approved these changes

2020-12-22 18:00 UTC, merged