feature/CU-bgucab_Create-an-UI-to-set-turns-count
Horsemen-and-Women-of-the-Apocalypse/bowling pull request #8
Opened 2020-12-22 23:57 UTC by Fantorem

2020-12-22 23:57 UTC, Fantorem commented
Task linked: [CU-bgucab Create an UI to set turns count](https://app.clickup.com/t/bgucab)

2020-12-23 16:10 UTC, Tomansion commented on src/views/Turn.vue
> +.md-icon {
Tu veux centrer horizontalement et verticalement le '+' et le '-' ?

En utilisant par exemple les flex
```css
  display: flex;
  align-items: center;
  justify-content: center;
```

2020-12-23 16:14 UTC, Tomansion commented on src/views/Turn.vue
> +          <md-icon>-</md-icon>
Tu veux pas utiliser un meilleur symbol ? du genre un svg ?
https://iconmonstr.com/minus-2-svg/ par exemple

2020-12-23 16:16 UTC, Tomansion commented on src/views/Turn.vue
> +const turn = Vue.observable({ count: 1 }) // Global access to number of turn
Vous voulez pas utiliser la gestion des états vuex? 
Un store existe déjà

2020-12-23 18:13 UTC, Thurstag requested changes

2020-12-23 18:13 UTC, Thurstag commented on src/views/Turn.vue
> +.md-icon {
Pas nécessaire si tu utilises de la bonne façon le md-icon

2020-12-23 18:13 UTC, Thurstag commented on src/views/Turn.vue
> +  background-color: #88A65E !important;
Vous pouvez changer la palette (https://vuematerial.io/themes/configuration) pour match la spec de @furtivesock

2020-12-23 18:13 UTC, Thurstag commented on src/views/Turn.vue
> +      font-size: 1em;
Regardes si https://vuematerial.io/ui-elements/typography offre de la responsiveness

2020-12-23 18:13 UTC, Thurstag commented on src/views/Turn.vue
> +  -moz-appearance: textfield;
Pourquoi tu fais ça ? (même question que le truc juste au dessus)

2020-12-23 18:15 UTC, Thurstag commented
Ton screen smartphone c'est un zoom ou une tablette ? safistaite du style @furtivesock ?

Ils sont où tes tests unitaires ? (https://vue-test-utils.vuejs.org/guides/#getting-started)

2020-12-23 18:19 UTC, Fantorem commented on src/views/Turn.vue
> +  -moz-appearance: textfield;
Enlever le +,- par défaut du type "number" sur l'input

2020-12-23 18:19 UTC, furtivesock commented
Les couleurs ont bien été reprises :smile: J'imagine que ça va être amélioré après mais les inputs ne sont pas très sexy... 

Ah au fait la police *desing* c'est  Spicy Rice.

2020-12-23 18:24 UTC, Fantorem commented
@Thurstag screen taille Iphone 5x.

2020-12-23 18:27 UTC, Thurstag commented
> @Thurstag screen taille Iphone 5x.

![](https://i.kym-cdn.com/entries/icons/original/000/023/021/e02e5ffb5f980cd8262cf7f0ae00a4a9_press-x-to-doubt-memes-memesuper-la-noire-doubt-meme_419-238.png)

2020-12-23 18:30 UTC, Fantorem commented
![Uploading image.png…]()

2020-12-23 18:34 UTC, Fantorem commented on src/views/Turn.vue
> +  background-color: #88A65E !important;
A intégrer dans les tâches d'init

2020-12-23 19:23 UTC, Fantorem commented
> Les couleurs ont bien été reprises 😄 J'imagine que ça va être amélioré après mais les inputs ne sont pas très sexy...
> 
> Ah au fait la police _desing_ c'est Spicy Rice.

Comment ça ?

2020-12-23 22:46 UTC, Thurstag commented
maj des screens ?

2020-12-24 08:35 UTC, Fantorem commented
> maj des screens ?

Il y a pas eu de maj sur l'ui

2020-12-24 15:28 UTC, Thurstag commented
> > maj des screens ?
> 
> Il y a pas eu de maj sur l'ui.
> Je laisse l'ui comme ça en attendant un fix pour le thème

tu as fix les boutons donc le rendu à changé

2020-12-24 15:46 UTC, Fantorem commented
> > > maj des screens ?
> > 
> > 
> > Il y a pas eu de maj sur l'ui.
> > Je laisse l'ui comme ça en attendant un fix pour le thème
> 
> tu as fix les boutons donc le rendu a changé et j'ai toujours pas de screen sur un écran de téléphone (celui que tu as mis a le ratio d'une tablette et non d'un téléphone)

Done

2020-12-24 15:47 UTC, Fantorem commented
![image](https://user-images.githubusercontent.com/32369396/103097463-9c8af580-4607-11eb-8f6c-541393b4f53b.png)
Et c'est bien un téléphone, il y a juste le composant pour choisir.

2020-12-24 15:52 UTC, Thurstag commented
Ah oui, je ne valide pas si il n'y a pas de tests unitaires sachant que c'est possible avec vue-test-utils

2020-12-24 17:34 UTC, Thurstag requested changes

2020-12-24 17:34 UTC, Thurstag commented on src/views/Turn.vue
> +          <md-input :value="turnCount" type="number" name="turnCount">{{turnCount}}</md-input>
On peut changer la valeur manuellement ? car si c'est pas le cas il faut rajouter `readonly` (cf: l'exemple read only de https://vuematerial.io/components/input#)

2020-12-24 17:34 UTC, Thurstag commented on tests/unit/turn.spec.js
> +describe('turn', () => {
Il y a plein de warnings dans la console des tests et pas de tests sur l'update GUI. Voilà une version propre des tests:

```js
import { mount } from '@vue/test-utils'
import Vue from 'vue'
import Turn from '../../src/views/Turn.vue'
import VueMaterial from 'vue-material'

/**
 * Mount a mocked version of Turn component
 *
 * @return {Wrapper<Turn>} Turn component
 */
const mountComponent = () => {
  return mount(Turn, {
    mocks: {
      $t: () => 'i18n is mocked' // Mock i18n function
    }
  })
}

const InputSelector = '[name=turnCount]';
const MinusButtonSelector = '#minus';
const AddButtonSelector = '#add';

beforeAll(() => {
  // Install vue-material components
  Vue.use(VueMaterial)
})

describe('TurnComponent', () => {
  test('add', async () => {
    const wrapper = mountComponent()

    await wrapper.find(AddButtonSelector).trigger('click')

    expect(wrapper.vm.turnCount).toBe(2)
    expect(wrapper.find(InputSelector).element.value).toBe('2')
  })

  test('minus', async () => {
    const wrapper = mountComponent()

    await wrapper.find(AddButtonSelector).trigger('click')
    await wrapper.find(AddButtonSelector).trigger('click')
    await wrapper.find(MinusButtonSelector).trigger('click')

    expect(wrapper.vm.turnCount).toBe(2)
    expect(wrapper.find(InputSelector).element.value).toBe('2')
  })

  test('minusTo0', async () => {
    const wrapper = mountComponent()

    await wrapper.find(MinusButtonSelector).trigger('click')

    expect(wrapper.vm.turnCount).toBe(1)
    expect(wrapper.find(InputSelector).element.value).toBe('1')
  })
})

```

2020-12-26 16:35 UTC, furtivesock commented on src/views/Turn.vue
> +          <md-input :value="turnCount" type="number" name="turnCount">{{turnCount}}</md-input>
Oui, le nombre de tours peut être modifiée manuellement pendant le wizard.

2020-12-28 17:46 UTC, Thurstag requested changes

2020-12-28 17:46 UTC, Thurstag commented on tests/unit/turn.spec.js
> +    wrapper.find('.md-input').element.dispatchEvent(new Event('blur'))
`wrapper.find(InputSelector).trigger('blur')`

2020-12-28 18:06 UTC, Thurstag approved these changes

2020-12-28 19:58 UTC, YesLife approved these changes

2020-12-28 20:01 UTC, Tomansion approved these changes

2020-12-28 21:20 UTC, merged