feature/CU-bguca0_Create-an-UI-to-set-pins-count
Horsemen-and-Women-of-the-Apocalypse/bowling pull request #9
Opened 2020-12-29 11:19 UTC by YesLife

2020-12-29 11:19 UTC, YesLife commented
Task linked: [CU-bguca0 Create an UI to set pins count](https://app.clickup.com/t/bguca0)

2020-12-29 11:40 UTC, YesLife commented
PC : 
![image](https://user-images.githubusercontent.com/70711818/103281403-fb1eed80-49d2-11eb-9262-2dd47e9ca75d.png)
Téléphone :
![image](https://user-images.githubusercontent.com/70711818/103281381-f0fcef00-49d2-11eb-958e-4dea41934880.png)

2020-12-29 17:40 UTC, Thurstag requested changes

2020-12-29 17:40 UTC, Thurstag commented on tests/unit/pins.spec.js
> + * Mount a mocked version of Turn component
`Mount a mocked version of Pins component`

2020-12-29 17:40 UTC, Thurstag commented on tests/unit/pins.spec.js
> + * @return {Wrapper<Turn>} Turn component
`@return {Wrapper<Pins>} Pins component`

2020-12-29 17:47 UTC, Thurstag approved these changes

2020-12-29 17:47 UTC, Thurstag commented on src/views/Pins.vue
> +    getPins () { // Method to get the number of pins
`pinsCount ()` pour le coverage de 100%

2020-12-29 17:49 UTC, Thurstag requested changes

2020-12-29 17:49 UTC, Thurstag commented on src/views/Pins.vue
> +    getPins () { // Method to get the number of pins
`pinsCount ()` pour le coverage de 100%

2020-12-29 18:07 UTC, Tomansion approved these changes

2020-12-29 19:38 UTC, Thurstag approved these changes

2020-12-30 00:19 UTC, Fantorem approved these changes

2020-12-30 07:06 UTC, merged